# Generated by Django 5.1.15 on 2026-07-05 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DianEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dian_environment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssuerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=50)),
                ('dv', models.CharField(blank=True, default='', max_length=5)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dian_environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dian.dianenvironment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'dian_issuer_company',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DianDocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dian_logs', to='tenants.tenant')),
                ('issuer_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_logs', to='dian.issuercompany')),
            ],
            options={
                'db_table': 'dian_document_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
