# Generated by Django 5.1.15 on 2026-07-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_tax_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproviderlink',
            name='provider_status',
            field=models.CharField(choices=[('NOT_REGISTERED', 'No registrada'), ('PENDING_CREATION', 'Creación pendiente'), ('REGISTERED', 'Registrada'), ('PENDING_UPDATE', 'Actualización pendiente'), ('SYNC_ERROR', 'Error de sincronización'), ('REMOTE_CREATED_IDENTIFIERS_PENDING', 'Identificadores MATIAS pendientes'), ('REMOTE_DISABLED', 'Desactivada en proveedor'), ('DELETION_PENDING', 'Desactivación pendiente'), ('REMOTE_NOT_FOUND', 'No encontrada en proveedor')], default='NOT_REGISTERED', max_length=40),
        ),
    ]
