# Generated by Django 5.1.15 on 2026-07-20 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companyproviderlink_provider_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='environment',
            field=models.CharField(default='sandbox', max_length=20),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['environment', 'nit'], name='companies_env_nit_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['environment', 'email'], name='companies_env_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('environment', 'nit'), name='unique_company_nit_per_environment'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('environment', 'email'), name='unique_company_email_per_environment'),
        ),
    ]
