# Generated by Django 5.1.15 on 2026-07-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_users', models.PositiveIntegerField(default=1)),
                ('max_issuers', models.PositiveIntegerField(default=1)),
                ('max_documents_per_month', models.PositiveIntegerField(default=0)),
                ('has_inventory', models.BooleanField(default=False)),
                ('has_cash_register', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans_plan',
                'ordering': ['monthly_price'],
            },
        ),
    ]
